# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: Komplexity

  # A short description of the repository that will show up on GitHub
  description: KSC building levels spread out to ten levels instead of the stock four levels. For Kerbal Space Program

  # A URL with more information about the repository
  homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/202749-*

  # A comma-separated list of topics to set on the repository
  topics: custombarnkit, github, mod, kerbal, kerbalspaceprogram, ksp, ksp-mods, kerbal-space, kerbal-space-program, kerbal-mods, ckan, curseforge, spacedock, zer0Kerbal, zedk

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: true

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: master


# Labels: define labels for Issues and Pull Requests
labels:
  - name: Version 0.9.9.9-prerelease
    # If including a `#`, make sure to wrap it with quotes!
    color: 336699
    description: last prerelease before full release.

# Milestones: define milestones for Issues and Pull Requests
milestones:
  - title: Version 0.9.9.9-prerelease
    description: Version 0.9.9.9-prerelease - last prerelease before full release.
    # The state of the milestone. Either `open` or `closed`
    state: open
