# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: Komplexity

  # A short description of the repository that will show up on GitHub
  description: KSC building levels spread out to ten levels instead of the stock four levels. For Kerbal Space Program

  # A URL with more information about the repository
  homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/202749-*

  # A comma-separated list of topics to set on the repository
  topics: custombarnkit, strategia, jnsq, mod, kerbal, kerbalspaceprogram, ksp, ksp-mods, kerbal-space, kerbal-space-program, kerbal-mods, zedk

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: true

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: master

# Labels: define labels for Issues and Pull Requests
labels:
  - name: Version 0.9.9.9-prerelease
    # If including a `#`, make sure to wrap it with quotes!
    color: 336699
    description: last prerelease before full release.

  - name: Version 0.9.9.9.1-prerelease
    # If including a `#`, make sure to wrap it with quotes!
    color: 336699
    description: last-last prerelease before  release.

  - name: Version 1.0.0.0-release
    # If including a `#`, make sure to wrap it with quotes!
    color: 336699
    description: full release.

  - name: adoption
    # If including a `#`, make sure to wrap it with quotes!
    color: BADA55
    description: relating to adoption

  - name: help wanted
    color: 008672
    description: "assistance, help, input solicited"

  - name: "semantic: release"
    color: 00FF00
    description: release

  - name: "semantic: prerelease"
    color: 00FF00
    description: prerelase

  - name: "semantic: beta"
    color: 00FF00
    description: beta

  - name: "semantic: alpha"
    color: 00FF00
    description: alpha

  - name: "type: localization"
    color: FFFFF0
    description: related to localization and translations

  - name: "type: infrastructure"
    color: ffdda8
    description: improvements or additions to project infrastructure
   
  - name: "type: automation"
    color: fbca04
    description: issues for automation actions

  - name: "issue: text"
    color: FBCA04
    description: issue type

  - name: "issue: compatibility/patch"
    color: CC0DEB
    description: issue type

  - name: "issue: model"
    color: FBCA04
    description: issue type

  - name: "issue: texture"
    color: FBCA04
    description: issue type

  - name: "issue: sound"
    color: FBCA04
    description: issue type

  - name: "issue: config"
    color: FBCA04
    description: issue type

  - name: "issue: code"
    color: FBCA04
    description: issue type

  - name: "issue: documentation"
    color: FBCA04
    description: issue type

  - name: "issue: relationship"
    color: FBCA04
    description: issue type

  - name: "issue: license"
    color: FBCA04
    description: issue type

  - name: "issue: install"
    color: FBCA04
    description: issue type

  - name: "issue: other"
    color: FBCA04
    description: issue type

  - name: "work: choatic"
    color: FBCA04
    description: The situation is chaotic, novel practices used.

  - name: "work: complex"
    color: d4c5f9
    description: The situation is complex, emergent practices used.

  - name: "work: complicated"
    color: ffb8c6
    description: The situation is complicated, good practices used.

  - name: "work: obvious"
    color: 91ca55
    description: The situation is obvious, best practices used.
    
  - name: "type: fix"
    color: 91ca55
    description: Iterations on existing features or infrastructure.
    
  - name: "type: testing"
    color: fbca04
    description: Related to testing.
    
  - name: "type: chore"
    color: fef2c0
    description: Converting measurements, reorganizing folder structure, and other necessary (but less impactful) tasks.
    
  - name: "type: discussion"
    color: d4c5f9
    description: Questions, queries, posers, proposals and info that requires discussion.
    
  - name: "type: docs"
    color: fef2c0
    description: Related to documentation and information.

  - name: "type: feature"
    color: 5ebeff
    description: Brand new functionality, features, pages, workflows, endpoints, etc.

  - name: "type: request"
    color: 5ebeff
    description: Brand new functionality, features, pages, workflows, endpoints, etc.

  - name: "type: fix"
    color: 91ca55
    description: Iterations on existing features or infrastructure.

  - name: "state: approved"
    color: 91ca55
    description: Approved to proceed.

  - name: "state: blocked"
    color: d73a4a
    description: Something is blocking action.

  - name: "state: pending"
    color: fbca04
    description: Taking action, but need a few things to happen first. A feature that needs dependencies merged, or a bug that needs further data.

  - name: "state: inactive"
    color: e6e6e6
    description: No action needed or possible. The issue is either fixed, addressed better by other issues, or just out of product scope.

  - name: "state: planning"
    color: FFFF00
    description: 

  - name: "state: inactive"
    color: e6e6e6
    description: No action needed or possible. The issue is either fixed, addressed better by other issues, or just out of product scope.

  - name: "type: upstream"
    color: FFFFF0
    description: upstream or side stream

  - name: "type: archive"
    color: FFFFF0
    description: archive

  - name: bug
    color: CC0000
    new_name: "type: type: bug"
    description: An issue with the system 🐛. Something isn't working... KSC... we have an error code

# Milestones: define milestones for Issues and Pull Requests
milestones:
  - title: Version 0.9.9.9-prerelease
    description: Version 0.9.9.9-prerelease - last prerelease before full release.
    # The state of the milestone. Either `open` or `closed`
    state: closed
  
  - title: Version 0.9.9.9.1-prerelease
    description: Version 0.9.9.9-prerelease - last prerelease before full release.
    # The state of the milestone. Either `open` or `closed`
    state: open
  
  - title: Version 1.0.0.0-release
    description: Version 1.0.0.0-release - last full release.
    # The state of the milestone. Either `open` or `closed`
    state: open
